services:
  db:
    image: postgres:17-alpine
    container_name: fm_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: football_db
    ports:
      - '5433:5432'
    volumes:
      - pgdata_new:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    image: footballmanager:latest
    container_name: fm_app
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/football_db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mysecretpassword

volumes:
  pgdata_new:
