# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: footballManager
    password:

jhipster:
  security:
    remember-me:
      key: d8c9dff1f387e7bdd0442cf390797ada8b13e7be802e31fd23711fc6e4266353f06e5ade92c820aec42fa66bf7d4514696bc
